### PR TITLE
Cars list

### LINKED ISSUE #8: [1pt] - Add Frontend Cars list page - Faranosh
- [ ] Add cars list React component.
- [ ] Add styles for resorts component.
- [ ] Add Redux async thunk API requests to fetch all the cars.

On the main page, the user can see a [Resorts](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005577).

### LINKED ISSUE #14: [2pt] Add Navigation -Sunga
In the navigation panel, the user can see links to:
Resorts:
"Reserve" form.
"My reservations".
"Add Resort" (the link is visible to everybody).
"Delete Resort" (the link is visible to everybody).

### PR DESCRIPTION
**Pull request by sunga12**
In the Cars List Page:

- Cars list React component.
- Add styles for car component.
- Add Redux async API requests to fetch all the cars.

In the navigation panel, the user can see links to:

- "New reservations" form.
- "My reservations".
- "Add Car" (the link is visible to everybody).
- "Delete Car" (the link is visible to everybody).
- Add styles for navigation.

### CODE REVIEW

**Comment by hmunish** [comment]
@sunga12 are you done working on this task?

**Comment by sunga12** [comment]
@hmunish no not yet, still working on it.

**Comment by hmunish** [comment]
@sunga12, I have added the required styles for the navbar & cars list. Now, everything seems to be working fine. It's time to merge it.

**Review by hmunish — APPROVED** [review]
@sunga12, I have added the required styles for the navbar & cars list. Now, everything seems to be working fine. It's time to merge it.

**Pull request merged**
